spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lune?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis:
  mapper-locations: /mapper/*.xml
  type-aliases-package: com.example.lune.domain
server:
  port: 8833